### ISSUE TITLE
WhoopsDisplayer

### ISSUE THREAD

**Issue by josephrexme** [jadz/laravel-framework-4.2.18-php7#1]
After following the instructions for set up in _composer.json_ and running `composer update`, I still get:

```
> php artisan clear-compiled
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Whoops\Run::handleException() must be an instance of Exception, instance of Error given, called in /home/vagrant/laravelProject/vendor/laravel/framework/src/Illuminate/Exception/WhoopsDisplayer.php on line 49 and defined in /home/vagrant/laravelProject/vendor/filp/whoops/src/Whoops/Run.php:233
Stack trace:
#0 /home/vagrant/laravelProject/vendor/laravel/framework/src/Illuminate/Exception/WhoopsDisplayer.php(49): Whoops\Run->handleException(Object(Error))
#1 /home/vagrant/laravelProject/vendor/laravel/framework/src/Illuminate/Exception/Handler.php(280): Illuminate\Exception\WhoopsDisplayer->display(Object(Error))
#2 /home/vagrant/laravelProject/vendor/laravel/framework/src/Illuminate/Exception/Handler.php(159): Illuminate\Exception\Handler->displayException(Object(Error))
#3 /home/vagrant/laravelProject/vendor/laravel/framework/src/Illuminate/Exception/Handler.php(170): Illuminate\Exception\Handler->handleException(Object(Error))
#4 [internal function]: in /home/vagrant/laravelProject/vendor/filp/whoops/src/Whoops/Run.php on line 233
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Uncaught TypeError: Argument 1 passed to Whoops\\Run::handleException() must be an instance of Exception, instance of Error given, called in \/home\/vagrant\/laravelProject\/vendor\/laravel\/framework\/src\/Illuminate\/Exception\/WhoopsDisplayer.php on line 49 and defined in \/home\/vagrant\/laravelProject\/vendor\/filp\/whoops\/src\/Whoops\/Run.php:233\nStack trace:\n#0 \/home\/vagrant\/laravelProject/vendor\/laravel\/framework\/src\/Illuminate\/Exception\/WhoopsDisplayer.php(49): Whoops\\Run->handleException(Object(Error))\n#1 \/home\/vagrant\/laravelProject\/vendor\/laravel\/framework\/src\/Illuminate\/Exception\/Handler.php(280): Illuminate\\Exception\\WhoopsDisplayer->display(Object(Error))\n#2 \/home\/vagrant\/laravelProject\/vendor\/laravel\/framework\/src\/Illuminate\/Exception\/Handler.php(159): Illuminate\\Exception\\Handler->displayException(Object(Error))\n#3 \/home\/vagrant\/laravelProject\/vendor\/laravel\/framework\/src\/Illuminate\/Exception\/Handler.php(170): Illuminate\\Exception\\Handler->handleException(Object(Error))\n#4 [internal function]:","file":"\/home\/vagrant\/laravelProject\/vendor\/filp\/whoops\/src\/Whoops\/Run.php","line":233}}Script php artisan clear-compiled handling the post-update-cmd event returned with an error



  [RuntimeException]                                                                                                                                                                                       
  Error Output: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Whoops\Run::handleException() must be an instance of Exception, instance of Error given, called in /home/vagrant/laravelProject/vendor/laravel/framework/src/Illuminate/Exception/WhoopsDisplayer.php on line 49 and defined in /home/vagrant/laravelProject/vendor/filp/whoops/src/Whoops/Run.php:233                           
  Stack trace:                                                                                                                                                                                             
  #0 /home/vagrant/laravelProject/vendor/laravel/framework/src/Illuminate/Exception/WhoopsDisplayer.php(49): Whoops\Run->handleException(Object(Error))                                                 
  #1 /home/vagrant/laravelProject/vendor/laravel/framework/src/Illuminate/Exception/Handler.php(280): Illuminate\Exception\WhoopsDisplayer->display(Object(Error))                                      
  #2 /home/vagrant/laravelProject/vendor/laravel/framework/src/Illuminate/Exception/Handler.php(159): Illuminate\Exception\Handler->displayException(Object(Error))                                     
  #3 /home/vagrant/laravelProject/vendor/laravel/framework/src/Illuminate/Exception/Handler.php(170): Illuminate\Exception\Handler->handleException(Object(Error))                                      
  #4 [internal function]: in /home/vagrant/laravelProject/vendor/filp/whoops/src/Whoops/Run.php on line 233                                                                                             

```

**Comment by jadz** [comment]
@bl4ckdu5t Have you tried clearing the application cache?

$ php artisan clear-compiled
$ php artisan clear:cache

**Comment by josephrexme** [comment]
The error wouldn't even let any artisan command work fine

**Comment by jadz** [comment]
I misread the error and had forgotten that I had fixed this manually myself.

The issue is because v1.1.10 of Whoops hasn't fixed the PHP7 compatibility issues (https://github.com/filp/whoops/issues/341 / https://github.com/filp/whoops/pull/284).

I haven't tried this myself, but you could try bumping the required version of whoops to be dev-master.

The reason why artisan commands won't be running is because there is likely an error somewhere in your application that is executed during the boot up of the application framework. (A service provider has a syntax error for example).

**Comment by josephrexme** [comment]
Thanks @jadz . I'll try to figure it out. It just turns out whoops isn't in composer.json to bump its version. I'll try to figure it out but if you can help by making me understand how you think I can change my version of whoops I'd appreciate it.

**Comment by jadz** [comment]
:+1: 

Whoops is located in the composer.json file of this repository
https://github.com/jadz/laravel-framework-4.2.18-php7/blob/master/composer.json#L17

**Comment by josephrexme** [comment]
Thanks

**Comment by jadz** [comment]
@bl4ckdu5t 

I've updated the composer.json file to include whoops's 2.0.0-alpha2 version.

In order to have it successfully pulled in, you will _need_ to make sure your minimum-stability is 'alpha' in your own composer.json file.

E.g:
"minimum-stability": "alpha"

**Comment by namaljayathunga** [comment]
I had a problem with updating. I did thees things.
Find `"filp/whoops"` from `composer.lock` under `require` and change it to 
`"filp/whoops": "2.0.0@alpha"`
then run bellow composer command.
`composer update filp/whoops:2.0.0@alpha`
Boom It's work. Thanks

**Comment by valmirphp** [comment]
Achei a solução pra min nesse link: https://github.com/laravel/framework/issues/9601

**Comment by larslemos** [comment]
@valmirphp  Estou a fazer refactoring de 1 codigo em producao de um Sistema de saude.
E tenho o mesmo error, li o link e  nao percebi como achaste a solucao.

**Comment by valmirphp** [comment]
@larslemos  isso já foi resolvido no Laravel 4.2.
Se vc der um composer update isso deve ser normalizar.
